version: "3.3"
services:
  python:
    build: .
    volumes:
      - ./.ingest-data:/app/.ingest-data
    links:
      - db
    depends_on:
      - db
    environment:
      POSTGRESQL_DATABASE: CODE_CHALLENGE
      POSTGRESQL_IP: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
  db:
    image: postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      - db